### ISSUE TITLE
@tf.function made loss difference 

### ISSUE THREAD

**Issue by StevenJokess** [biswajitsahoo1111/D2L_Generative_Adversarial_Networks_in_TF#1]
http://preview.d2l.ai/d2l-en/PR-1716/chapter_generative-adversarial-networks/gan.html
![image](https://user-images.githubusercontent.com/71307974/120439021-9ec25e80-c3b4-11eb-8511-68c7203ff6db.png)

**Comment by biswajitsahoo1111** [comment]
@StevenJokess, I ran the notebook after including `@tf.function` and got approximately same loss values. Please check this gist: https://gist.github.com/biswajitsahoo1111/0076d623a66bef3f5ffb299daaf27691

You can run the notebook of this repo yourself by including `@tf.function`. You will most likely get similar learning curves. I am not sure why you got an irregular learning curve while your training. An obvious option would be to rerun the notebook and check again.
